export const nigeriaCourtsLocations = [
    { state: "Abia", courtsLocation: "Umuahia" },
    { state: "Adamawa", courtsLocation: "Yola" },
    { state: "Akwa Ibom", courtsLocation: "Uyo" },
    { state: "Anambra", courtsLocation: "Awka" },
    { state: "Bauchi", courtsLocation: "Bauchi" },
    { state: "Bayelsa", courtsLocation: "Yenagoa" },
    { state: "Benue", courtsLocation: "Makurdi" },
    { state: "Borno", courtsLocation: "Maiduguri" },
    { state: "Cross River", courtsLocation: "Calabar" },
    { state: "Delta", courtsLocation: "Asaba" },
    { state: "Ebonyi", courtsLocation: "Abakaliki" },
    { state: "Edo", courtsLocation: "Benin City" },
    { state: "Ekiti", courtsLocation: "Ado-Ekiti" },
    { state: "Enugu", courtsLocation: "Enugu" },
    { state: "Gombe", courtsLocation: "Gombe" },
    { state: "Imo", courtsLocation: "Owerri" },
    { state: "Jigawa", courtsLocation: "Dutse" },
    { state: "Kaduna", courtsLocation: "Kaduna" },
    { state: "Kano", courtsLocation: "Kano" },
    { state: "Katsina", courtsLocation: "Katsina" },
    { state: "Kebbi", courtsLocation: "Birnin Kebbi" },
    { state: "Kogi", courtsLocation: "Lokoja" },
    { state: "Kwara", courtsLocation: "Ilorin" },
    { state: "Lagos", courtsLocation: "Ikeja" },
    { state: "Nasarawa", courtsLocation: "Lafia" },
    { state: "Niger", courtsLocation: "Minna" },
    { state: "Ogun", courtsLocation: "Abeokuta" },
    { state: "Ondo", courtsLocation: "Akure" },
    { state: "Osun", courtsLocation: "Osogbo" },
    { state: "Oyo", courtsLocation: "Ibadan" },
    { state: "Plateau", courtsLocation: "Jos" },
    { state: "Rivers", courtsLocation: "Port Harcourt" },
    { state: "Sokoto", courtsLocation: "Sokoto" },
    { state: "Taraba", courtsLocation: "Jalingo" },
    { state: "Yobe", courtsLocation: "Damaturu" },
    { state: "Zamfara", courtsLocation: "Gusau" },
    { state: "Federal Capital Territory", courtsLocation: "Abuja" }
];
export const nigeriaCourts = [
    { state: "Abia", jurisdictions: ["State High Court", "Federal High Court", "Customary Court of Appeal", "Magistrate Court"] },
    { state: "Adamawa", jurisdictions: ["State High Court", "Federal High Court", "Sharia Court of Appeal", "Magistrate Court"] },
    { state: "Akwa Ibom", jurisdictions: ["State High Court", "Federal High Court", "Customary Court of Appeal", "Magistrate Court"] },
    { state: "Anambra", jurisdictions: ["State High Court", "Federal High Court", "Customary Court of Appeal", "Magistrate Court"] },
    { state: "Bauchi", jurisdictions: ["State High Court", "Federal High Court", "Sharia Court of Appeal", "Magistrate Court"] },
    { state: "Bayelsa", jurisdictions: ["State High Court", "Federal High Court", "Customary Court of Appeal", "Magistrate Court"] },
    { state: "Benue", jurisdictions: ["State High Court", "Federal High Court", "Customary Court of Appeal", "Magistrate Court"] },
    { state: "Borno", jurisdictions: ["State High Court", "Federal High Court", "Sharia Court of Appeal", "Magistrate Court"] },
    { state: "Cross River", jurisdictions: ["State High Court", "Federal High Court", "Customary Court of Appeal", "Magistrate Court"] },
    { state: "Delta", jurisdictions: ["State High Court", "Federal High Court", "Customary Court of Appeal", "Magistrate Court"] },
    { state: "Ebonyi", jurisdictions: ["State High Court", "Federal High Court", "Customary Court of Appeal", "Magistrate Court"] },
    { state: "Edo", jurisdictions: ["State High Court", "Federal High Court", "Customary Court of Appeal", "Magistrate Court"] },
    { state: "Ekiti",  jurisdictions: ["State High Court", "Federal High Court", "Customary Court of Appeal", "Magistrate Court"] },
{ state: "Enugu", jurisdictions: ["State High Court", "Federal High Court", "Customary Court of Appeal", "Magistrate Court"] },
{ state: "Gombe", jurisdictions: ["State High Court", "Federal High Court", "Sharia Court of Appeal", "Magistrate Court"] },
{ state: "Imo", jurisdictions: ["State High Court", "Federal High Court", "Customary Court of Appeal", "Magistrate Court"] },
{ state: "Jigawa", jurisdictions: ["State High Court", "Federal High Court", "Sharia Court of Appeal", "Magistrate Court"] },
{ state: "Kaduna", jurisdictions: ["State High Court", "Federal High Court", "Sharia Court of Appeal", "Magistrate Court"] },
{ state: "Kano", jurisdictions: ["State High Court", "Federal High Court", "Sharia Court of Appeal", "Magistrate Court"] },
{ state: "Katsina", jurisdictions: ["State High Court", "Federal High Court", "Sharia Court of Appeal", "Magistrate Court"] },
{ state: "Kebbi", jurisdictions: ["State High Court", "Federal High Court", "Sharia Court of Appeal", "Magistrate Court"] },
{ state: "Kogi", jurisdictions: ["State High Court", "Federal High Court", "Customary Court of Appeal", "Magistrate Court"] },
{ state: "Kwara", jurisdictions: ["State High Court", "Federal High Court", "Sharia Court of Appeal", "Magistrate Court"] },
{ state: "Lagos", jurisdictions: ["State High Court", "Federal High Court", "Customary Court of Appeal", "Magistrate Court"] },
{ state: "Nasarawa", jurisdictions: ["State High Court", "Federal High Court", "Customary Court of Appeal", "Magistrate Court"] },
{ state: "Niger", jurisdictions: ["State High Court", "Federal High Court", "Sharia Court of Appeal", "Magistrate Court"] },
{ state: "Ogun", jurisdictions: ["State High Court", "Federal High Court", "Customary Court of Appeal", "Magistrate Court"] },
{ state: "Ondo", jurisdictions: ["State High Court", "Federal High Court", "Customary Court of Appeal", "Magistrate Court"] },
{ state: "Osun", jurisdictions: ["State High Court", "Federal High Court", "Customary Court of Appeal", "Magistrate Court"]},
{ state: "Oyo", jurisdictions: ["State High Court", "Federal High Court", "Customary Court of Appeal", "Magistrate Court"] },
{ state: "Plateau", jurisdictions: ["State High Court", "Federal High Court", "Sharia Court of Appeal", "Magistrate Court"] },
{ state: "Rivers", jurisdictions: ["State High Court", "Federal High Court", "Customary Court of Appeal", "Magistrate Court"] },
{ state: "Sokoto", jurisdictions: ["State High Court", "Federal High Court", "Sharia Court of Appeal", "Magistrate Court"] },
{ state: "Taraba", jurisdictions: ["State High Court", "Federal High Court", "Sharia Court of Appeal", "Magistrate Court"] },
{ state: "Yobe", jurisdictions: ["State High Court", "Federal High Court", "Sharia Court of Appeal", "Magistrate Court"] },
{ state: "Zamfara", jurisdictions: ["State High Court", "Federal High Court", "Sharia Court of Appeal", "Magistrate Court"] },
{ state: "Federal Capital Territory", jurisdictions: ["FCT High Court", "Federal High Court", "Customary Court of Appeal of the FCT", "Sharia Court of Appeal of the FCT"] }
];

export const nigerianStates = [
    "Abia", "Adamawa", "Akwa Ibom", "Anambra", "Bauchi", 
    "Bayelsa", "Benue", "Borno", "Cross River", "Delta", 
    "Ebonyi", "Edo", "Ekiti", "Enugu", "Gombe", 
    "Imo", "Jigawa", "Kaduna", "Kano", "Katsina", 
    "Kebbi", "Kogi", "Kwara", "Lagos", "Nasarawa", 
    "Niger", "Ogun", "Ondo", "Osun", "Oyo", 
    "Plateau", "Rivers", "Sokoto", "Taraba", "Yobe", 
    "Zamfara", "Federal Capital Territory"
];

